export const demoPlaces = [
  {
    id: "demo-1",
    name: "Finca Verde Panama",
    seller: "Maria Gonzalez",
    product: "Romaine lettuce",
    district: "Cerro Punta",
    township: "Guadalupe",
    address: "Guadalupe, Cerro Punta, Chiriquí",
    phone: "+507 6000-0001",
    latitude: 8.8794,
    longitude: -82.5665,
    keywords: ["lettuce", "romaine", "hydroponics", "farm"],
    active: true
  },
  {
    id: "demo-2",
    name: "Cultivos del Oeste",
    seller: "Carlos Mendez",
    product: "Tomato",
    district: "La Chorrera",
    township: "El Coco",
    address: "El Coco, La Chorrera",
    phone: "+507 6000-0002",
    latitude: 8.9142,
    longitude: -79.8063,
    keywords: ["tomato", "crops", "vegetables"],
    active: true
  },
  {
    id: "demo-3",
    name: "Huerto Familiar",
    seller: "Ana Rodriguez",
    product: "Spinach",
    district: "Arraiján",
    township: "Vista Alegre",
    address: "Vista Alegre, Arraiján",
    phone: "+507 6000-0003",
    latitude: 8.9277,
    longitude: -79.6968,
    keywords: ["spinach", "vegetables", "garden"],
    active: true
  },
  {
    id: "demo-4",
    name: "Agrocultivos del Pacifico",
    seller: "Monica Rivera",
    product: "Chives",
    district: "Boquete",
    township: "Alto Boquete",
    address: "Alto Boquete, Chiriquí",
    phone: "+507 6000-0004",
    latitude: 8.7833,
    longitude: -82.4342,
    keywords: ["chives", "cebollina", "herbs"],
    active: true
  },
  {
    id: "demo-5",
    name: "Jardines de Volcán",
    seller: "Roberto Sanchez",
    product: "Butterhead lettuce",
    district: "Volcán",
    township: "Volcán Centro",
    address: "Volcán Centro, Chiriquí",
    phone: "+507 6000-0005",
    latitude: 8.7667,
    longitude: -82.6333,
    keywords: ["lettuce", "butterhead", "vegetables", "farm"],
    active: true
  },
  {
    id: "demo-6",
    name: "Rábanos de Santa Fe",
    seller: "Luisa Herrera",
    product: "Radish",
    district: "Santa Fe",
    township: "Santa Fe Centro",
    address: "Santa Fe, Veraguas",
    phone: "+507 6000-0006",
    latitude: 8.8167,
    longitude: -81.1167,
    keywords: ["radish", "rabano", "vegetables"],
    active: true
  },
  {
    id: "demo-7",
    name: "Pimientos del Valle",
    seller: "Jorge Castillo",
    product: "Red bell peppers",
    district: "Dolega",
    township: "Potrerillos",
    address: "Potrerillos, Dolega, Chiriquí",
    phone: "+507 6000-0007",
    latitude: 8.6667,
    longitude: -82.4667,
    keywords: ["pepper", "bell pepper", "red", "vegetables"],
    active: true
  },
  {
    id: "demo-8",
    name: "Cultivos Bugaba",
    seller: "Patricia Vega",
    product: "Yellow bell peppers",
    district: "Bugaba",
    township: "Santo Domingo",
    address: "Santo Domingo, Bugaba, Chiriquí",
    phone: "+507 6000-0008",
    latitude: 8.4833,
    longitude: -82.6167,
    keywords: ["pepper", "bell pepper", "yellow", "vegetables"],
    active: true
  },
  {
    id: "demo-9",
    name: "Huerta Renacimiento",
    seller: "Fernando Ortiz",
    product: "Green bell peppers",
    district: "Renacimiento",
    township: "Rio Sereno",
    address: "Rio Sereno, Renacimiento, Chiriquí",
    phone: "+507 6000-0009",
    latitude: 8.8333,
    longitude: -82.8500,
    keywords: ["pepper", "bell pepper", "green", "vegetables"],
    active: true
  },
  {
    id: "demo-10",
    name: "Lechugas de Capira",
    seller: "Diana Morales",
    product: "Romaine lettuce",
    district: "Capira",
    township: "Cirí de Los Sotos",
    address: "Cirí de Los Sotos, Capira",
    phone: "+507 6000-0010",
    latitude: 8.7500,
    longitude: -79.8667,
    keywords: ["lettuce", "romaine", "farm"],
    active: true
  },
  {
    id: "demo-11",
    name: "Tomates de Chame",
    seller: "Ricardo Peña",
    product: "Tomato",
    district: "Chame",
    township: "Bejuco",
    address: "Bejuco, Chame",
    phone: "+507 6000-0011",
    latitude: 8.5667,
    longitude: -79.8833,
    keywords: ["tomato", "crops", "vegetables"],
    active: true
  },
  {
    id: "demo-12",
    name: "Espinacas de Cerro Punta",
    seller: "Yamileth Rios",
    product: "Spinach",
    district: "Cerro Punta",
    township: "Bajo Grande",
    address: "Bajo Grande, Cerro Punta, Chiriquí",
    phone: "+507 6000-0012",
    latitude: 8.8850,
    longitude: -82.5600,
    keywords: ["spinach", "vegetables", "garden"],
    active: true
  },
  {
    id: "demo-13",
    name: "Cebollina San Carlos",
    seller: "Nestor Aguilar",
    product: "Chives",
    district: "San Carlos",
    township: "El Espino",
    address: "El Espino, San Carlos, Panamá Oeste",
    phone: "+507 6000-0013",
    latitude: 8.5333,
    longitude: -80.0500,
    keywords: ["chives", "cebollina", "herbs"],
    active: true
  },
  {
    id: "demo-14",
    name: "Huerto David Norte",
    seller: "Gabriela Nuñez",
    product: "Butterhead lettuce",
    district: "David",
    township: "San Pablo Nuevo",
    address: "San Pablo Nuevo, David, Chiriquí",
    phone: "+507 6000-0014",
    latitude: 8.4600,
    longitude: -82.4100,
    keywords: ["lettuce", "butterhead", "vegetables"],
    active: true
  },
  {
    id: "demo-15",
    name: "Rábanos de Ocú",
    seller: "Manuel Solís",
    product: "Radish",
    district: "Ocú",
    township: "Ocú Centro",
    address: "Ocú, Herrera",
    phone: "+507 6000-0015",
    latitude: 7.9500,
    longitude: -80.7833,
    keywords: ["radish", "rabano", "vegetables"],
    active: true
  }
];